### ISSUE TITLE
Broken Article Link

### ISSUE THREAD

**Issue by resurtm** [EwanValentine/shippy#1]
Hi @EwanValentine!

Thank you for the article. I've stumbled upon two issues:

1. The link to the Github repo is broken:
![image](https://user-images.githubusercontent.com/100198/33039511-611365a2-ce62-11e7-99ef-b6dbc0eacc37.png)
It refers to: https://ewanvalentine.io/microservices-in-golang-part-1/github.com/ewanvalentine/shippy/
Not to (as it should be): https://github.com/EwanValentine/shippy/

2. Package name in the import statement is case sensitive. Also note `shippy` vs `shipper`.
https://github.com/EwanValentine/shippy/blob/tutorial-1/consignment-service/main.go#L8
Must be: `pb "github.com/EwanValentine/shippy/consignment-service/proto/consignment"`
Your code: `pb "github.com/ewanvalentine/shipper/consignment-service/proto/consignment"`

3. The same goes to CLI client: https://github.com/EwanValentine/shippy/blob/tutorial-1/consignment-cli/cli.go

Cheers,
@resurtm

**Comment by EwanValentine** [comment]
@resurtm great spot! Thank you! Really appreciate it :)
