### ISSUE TITLE
Tutorial 2: undefined: vessel.RegisterVesselServiceHandler

### ISSUE THREAD

**Issue by jpds** [EwanValentine/shippy#12]
For some reason, following the code on https://ewanvalentine.io/microservices-in-golang-part-2/ and using `golang:1.10.3-alpine3.7`, I get the following error while compiling `vessel-service`:

```
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .
# github.com/EwanValentine/shippy/vessel-service
./main.go:65:2: undefined: vessel.RegisterVesselServiceHandler
```

I've attached the [vessel.pb.go.txt](https://github.com/EwanValentine/shippy/files/2195024/vessel.pb.go.txt) file that was generated on my container. I can see that there's a `RegisterVesselServiceServer` where it looks like the `RegisterVesselServiceHandler` should be. I do not know why this is the case as there is no code diff between what I have copy and pasted and what's in this repo.

**Comment by spoonFedForehead** [comment]
getting the same issue with RegisterShippingServiceHandler

**Comment by yanlyan** [comment]
getting same issue, I think it's because of the generated `consignment.pb.go` using micro plugins

**Comment by kscarlett** [comment]
I think I have fixed this on my end. Newer versions of go-micro seem to generate the code for go-micro in a separate file.
To fix it, I removed the following line from the makefile:
```Makefile
protoc -I. --go_out=plugins=micro:$(GOPATH)/src/github.com/kscarlett/shippy/vessel-service  proto/vessel/vessel.proto
```
And added this line to replace it:
```Makefile
protoc --proto_path=$(GOPATH)/src:. --micro_out=. --go_out=. proto/vessel/vessel.proto
```

**Comment by TheApeMachine** [comment]
If you run into this error: protoc-gen-micro: program not found or is not executable, change to:

`protoc --plugin=protoc-gen-go=$(GOPATH)/bin/protoc-gen-go --plugin=protoc-gen-micro=$(GOPATH)/bin/protoc-gen-micro --proto_path=$(GOPATH)/src:. --micro_out=. --go_out=. proto/consignment/consignment.proto`
