### ISSUE TITLE
Tutorial 2: undefined: proto.ProtoPackageIsVersion3

### ISSUE THREAD

**Issue by yoavl** [EwanValentine/shippy#21]
Hi,
I keep getting this error on  make build

vendor/github.com/micro/go-micro/registry/gossip/proto/gossip.pb.go:21:11: undefined: proto.ProtoPackageIsVersion3

**Comment by yoavl** [comment]
follow by:
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .' returned a non-zero code: 2

**Comment by jfiuza** [comment]
I too have the same problem

**Comment by mqyang56** [comment]
> Hi,
> I keep getting this error on make build
> 
> vendor/github.com/micro/go-micro/registry/gossip/proto/gossip.pb.go:21:11: undefined: proto.ProtoPackageIsVersion3
set branch = "master"
[[constraint]]
  branch ="master"
  name = "github.com/golang/protobuf"

**Comment by mqyang56** [comment]
@yoavl
 [[constraint]]
  branch ="master"
  name = "github.com/golang/protobuf"

**Comment by codenakama** [comment]
@Amanda111 spent hours on this yesterday! thank you!
