### ISSUE TITLE
Dep init on dev environment

### ISSUE THREAD

**Issue by codenakama** [EwanValentine/shippy#22]
Shouldn't we run `dep init` on dev environment so then we just run `dep ensure` on the machine?
This is because I like to test things first on my machine and only after dockerize it. But if I do so, then running dep init again complains because Gopkg.toml file already exists. Also I think what gets installed on docker should be exactly the same as dev environment so its predictable - which I believe is assured by Gopkg.lock.

Thoughts?

**Comment by EwanValentine** [comment]
@codenakama I'm updating this to use go mod, should be done fairly soon, that should clear this up
