### ISSUE TITLE
Service 'consignment-cli' failed to build: The command '/bin/sh -c dep init && dep ensure' returned a non-zero code: 1

### ISSUE THREAD

**Issue by yangjie21** [EwanValentine/shippy#29]
![image](https://user-images.githubusercontent.com/19204745/62337295-a5f15a80-b506-11e9-9bbc-1f9862ed53af.png)

**Comment by Donng** [comment]
what's tutorial? the new posts use `go mod` instead of `dep`. I think you could change this first, just following this [link](https://ewanvalentine.io/microservices-in-golang-part-1/)

**Comment by EwanValentine** [comment]
Hey! I'm currently updating all of these and porting everything over to go mod, thanks!
