### ISSUE TITLE
Could not connect to DB: dial tcp: lookup database on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by jmesyan** [EwanValentine/shippy#31]
the tutorial 3 problem:
## I start the database,use the command:
```
docker-compose run database
```
- the result is
```
PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2019-09-22 10:08:20 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
```
it is ok
## when I start the user-service, the error is coming:
```
Could not connect to DB: dial tcp: lookup database on 127.0.0.11:53: no such host
```
how to solve the problem, my operating system is macos

**Comment by Birjemin** [comment]
have you been solved this problem?

**Comment by jmesyan** [comment]
you can choose docker-compose up all service, not start a service alone @Birjemin

**Comment by Birjemin** [comment]
> you can choose docker-compose up all service, not start a service alone @Birjemin

thank you!

**Comment by jmesyan** [comment]
不客气 @Birjemin
