### ISSUE TITLE
user-cli/cli.go fails to build when using go mod -- unable to find go-micro/cmd.

### ISSUE THREAD

**Issue by RichJames** [EwanValentine/shippy#32]
The maintainers of go-micro moved the cmd code into the config subdirectory of that module when they booked changes tagged at their version v1.8.0.  So now the location is "github.com/micro/go-micro/config/cmd".  With that one change to the import in cli.go, things will build correctly.

**Comment by EwanValentine** [comment]
@RichJames thank you! In the process of updating all of these now, so will address this, will leave this open until then
