### ISSUE TITLE
Getting error when downloading the dependencies of shippy-cli-consignment 

### ISSUE THREAD

**Issue by Qalifah** [EwanValentine/shippy#36]
Following the tutorial, i was able to build and run the image for the shippy-service-consignment but i'm having issues with the building of the shippy-cli-consignment image, it gets stuck at the `RUN go mod download` command.

Error message:
`go: github.com/Qalifah/shippy/shippy-service-consignment@v0.0.0-00010101000000-000000000000: parsing /shippy-service-consignment/go.mod: open /shippy-service-consignment/go.mod: no such file or directory `

what am i doing wrong?

**Comment by talaniz** [comment]
looks like you might have missed a step?

```
$ go mod init github.com/<YourUserName>/shippy/shippy-service-consignment
$ go get -u
```

**Comment by Qalifah** [comment]
I was able to resolve it...thank you.
