### ISSUE TITLE
Wrong Dockerfile for user-service

### ISSUE THREAD

**Issue by marceloaguero** [EwanValentine/shippy#6]
Apparently,Dockerfile for user-service was copied from the version for vessel-service. The following lines are wrong in user-service/Dockerfile

WORKDIR /go/src/github.com/EwanValentine/shippy/vessel-service

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

COPY --from=builder /go/src/github.com/EwnaValentine/shippy/vessel-service/vessel-service .
CMD ["./vessel-service"]

**Comment by moficodes** [comment]
@marceloaguero  saw the same. 
albeit a year later. 

i am just gonna use the user service for this. although this should be a pull request.

**Comment by EwanValentine** [comment]
These are all getting updated at the moment, so will be fixed soon :)
